# Generated by Django 4.2.2 on 2023-06-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_autor_comentario_rename_descricao_post_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
