# Generated by Django 4.2.2 on 2023-06-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_comentarios_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
        migrations.AddField(
            model_name='post',
            name='areas',
            field=models.ManyToManyField(to='blog.area'),
        ),
    ]
